### ISSUE TITLE
Use the "climat" HA function

### ISSUE THREAD

**Issue by weado** [FreeTHX/remora-ha#1]
Hello and thank you for the awesone HA plugin.

I would like to use this plugin like a thermostat, so the parameters doesn't work with it (as `target_sensor: sensor.study_temperature` ) to show all information of my house (temperature and heater configuration at least).

Thank you again !

**Comment by FreeTHX** [comment]
Hi @weado 
Use the async branch, which supports target_sensor to report temperature in real time to the climate object.
I have been testing it for 2 months, but I need external feedback before pushing it to the master branch.

**Comment by weado** [comment]
Hello, 
I just tested the remora from async branch and it works well for me. Thank you !
Will you add the other configurations to have a thermostat later ?

Merci !

**Comment by FreeTHX** [comment]
Salut,

I was thinking about it, but... heaters with 'fil pilote' provide only few options.
As an example, temperature control is restricted by the manually setup limites and so you can not exceed the 'Confort' temperature.
So right now, I prefer to keep it simple rather than to implement complex control_heating functions.

If you are thinking about a useful and/or "must have" configuration, feel free to ask or implement yourself.

**Comment by weado** [comment]
Salut, ;-)

Isn't it possible to change the control_heating in function of that you want : If you want hotter you change the control_heating to "hot" or if you want cooler, you switch to "eco" with tempo to avoid the multiple state changes  ?
It's just an idea, without know if it's possible, but I'm just looking for a solution to use completly the plugin (I'm not a developer).
Thank you again for your work.

**Comment by FreeTHX** [comment]
You can already change the preset as you want and so force the heater in Confort / Eco / HorsGel / Arret.
Here is my example using lovelace UI
![image](https://user-images.githubusercontent.com/16355105/70668830-f75be400-1c74-11ea-8f23-c1a9e7fb1c7b.png)
You can also use the icons one the card.
![image](https://user-images.githubusercontent.com/16355105/70668863-15c1df80-1c75-11ea-9866-2aff765c5471.png)

I will give you more inputs on the remora forum ;)
